datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  clusterName: corndog
  tags:
    - env:corndog-260318
  apm:
    portEnabled: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  networkMonitoring:
    enabled: true
  securityAgent:
    runtime:
      enabled: true
    compliance:
      enabled: true
      host_benchmarks:
        enabled: true
  sbom:
    enabled: true
    containerImage:
      enabled: true
    host:
      enabled: true
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager
    - kube_scheduler
  kubelet:
    tlsVerify: false
